---
- name: Ensure baseline software for distribution is installed
  ansible.builtin.package:
    name: "{{ baseline.packages }}"
    state: present
- name: Ensure ansible SSH key is authorized
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJIXb28FVVgoNBtMUO3KS7nBVPvAnP8cHuP97POlEU/ ansible"
- name: Ensure root password is locked
  ansible.builtin.user:
    name: root
    password_lock: true
- name: Ensure sshd is started
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
- name: Ensure sshd is configured
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: restart_sshd
