---
- name: Ensure the hostname is configured correctly
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  tags:
    - molecule-notest
- name: Ensure baseline packages are installed (Fedora)
  ansible.builtin.dnf:
    name: "{{ baseline.packages }}"
    state: latest
    update_cache: true
  when: ansible_distribution == "Fedora"
- name: Update apt cache and existing packages (Debian)
  ansible.builtin.apt:
    update_cache: true
    clean: true
    autoremove: true
    upgrade: full
  when: ansible_distribution == "Debian"
- name: Ensure baseline packages are installed (Debian)
  ansible.builtin.apt:
    name: "{{ baseline.packages }}"
    state: present
  when: ansible_distribution == "Debian"
- name: Ensure root password is locked
  ansible.builtin.user:
    name: root
    password_lock: true
