---
- name: Assert this host can use this role
  assert:
    that: ansible_distribution in supported_distributions
    fail_msg: "This role is not supported on your host operating system."
- name: Include OS specific variables
  include_vars: "{{ ansible_distribution | lower }}.yml"
- name: shell configuration
  include_tasks: "{{ ansible_user_shell | basename }}-config.yml"
- name: role packages
  include_tasks: "packages-{{ ansible_distribution | lower }}.yml"
- name: tmux configuration
  include_tasks: tmux.yml
- name: git configuration
  include_tasks: git.yml
- name: vim configuration
  include_tasks: vim.yml
