---
- name: Ensure baseline software for distribution is installed
  ansible.builtin.package:
    name: "{{ baseline.packages }}"
    state: present
- name: Ensure root password is locked
  ansible.builtin.user:
    name: root
    password_lock: yes
- name: Ensure sshd is started
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: yes
- name: Ensure sshd is configured
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: restart_sshd
