---
- name: Assert homebrew is installed
  ansible.builtin.assert:
    that: ansible_pkg_mgr == "homebrew"
    fail_msg: "A homebrew installation is required."
- name: Ensure baseline brews are installed
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - ansible-lint
    #- dockutil
    - git
    - tmux
    - vim
- name: Ensure baseline casks are installed
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - google-chrome
