---
- name: Assert homebrew is installed
  assert:
    that: ansible_pkg_mgr == "homebrew"
    fail_msg: "A homebrew installation is required."
- name: Ensure system brews are installed
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ system_brews }}"
  when:
    - system_brews is defined
    - (system_brews | length > 0)
- name: Ensure system casks are installed
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ system_casks }}"
  when:
    - system_casks is defined
    - (system_casks | length > 0)
