---
- name: Install cert-manager into the cluster
  hosts: localhost
  vars_files:
    - cnames.yaml
  tasks:
    - name: Ensure the helm repo for cert-manager is added
      kubernetes.core.helm_repository:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: jetstack
        repo_url: "https://charts.jetstack.io"
    - name: Ensure the cert-manager CRD configuration has been applied
      kubernetes.core.k8s:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        state: present
        src: https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml
    - name: Ensure the cert-manager helm chart is installed
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
