---
- name: Install Prometheus into the cluster
  hosts: localhost
  vars_files:
    - cnames.yaml
  tasks:
    - name: Ensure common packages are installed
      ansible.builtin.apt:
        name:
          - python3-kubernetes
        cache_valid_time: 300
        lock_timeout: 180
      become: true
    - name: Ensure the helm repo for prometheus is added
      kubernetes.core.helm_repository:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"
    - name: Ensure the prometheus helm chart is installed
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          server:
            ingress:
              enabled: true
              ingressClassName: traefik
              hosts:
                - "{{ cnames.prometheus }}"
    - name: Ensure the ingress configuration for the alertmanager has been applied
      kubernetes.core.k8s:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        state: present
        template: prometheus-ingress.yaml
