---
- name: Install Grafana into the cluster
  hosts: localhost
  vars_files:
    - cnames.yaml
  tasks:
    - name: Ensure the helm repo for grafana is added
      kubernetes.core.helm_repository:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: grafana
        repo_url: "https://grafana.github.io/helm-charts"
    - name: Ensure the grafana helm chart is installed
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: grafana
        chart_ref: grafana/grafana
        release_namespace: grafana
        create_namespace: true
        values:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - "{{ cnames.grafana }}"
          adminPassword: password
   # - name: Ensure the ingress configuration for the alertmanager has been applied
    #   kubernetes.core.k8s:
    #     kubeconfig: "{{ k3s_local_kubeconfig_path }}"
    #     state: present
    #     template:
    #       - path: grafana-ingress.yaml
    #         variable_start_string: '[['
    #         variable_end_string: ']]'
