---
- name: Common
  hosts: all
  environment:
    INSTALL_K3S_SKIP_START: true
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    K3S_TOKEN: "{{ k3s_token }}"
  tasks:
    - name: Ensure common packages are installed
      ansible.builtin.apt:
        name:
          - python3-kubernetes
          - cryptsetup
          - ipvsadm
          - jq
          - nfs-common
          - open-iscsi
          - parted
        cache_valid_time: 300
        lock_timeout: 180
      become: true
    - name: Ensure the iscsi_tcp module is loaded before iscsid is started
      community.general.modprobe:
        name: iscsi_tcp
      become: true
    - name: Ensure the iscsid service is enabled and started for longhorn
      ansible.builtin.systemd:
        name: iscsid
        state: restarted
        enabled: true
      become: true
    - name: Ensure the K3S drop-in configuration directory exists
      ansible.builtin.file:
        path: /etc/rancher/k3s/config.yaml.d
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true
    # - name: Ensure the second disk is partitioned
    #   community.general.parted:
    #     device: /dev/sdb
    #     label: gpt
    #     name: k3s_storage
    #     number: 1
    #     state: present
    #     fs_type: ext4
    #   become: true
    #   register: partitions
    # - name: Ensure any new partition is formatted
    #   community.general.filesystem:
    #     fstype: ext4
    #     dev: /dev/sdb1
    #   become: true
    #   when: partitions.changed
    # - name: Ensure storage disk is mounted
    #   ansible.posix.mount:
    #     path: /k3s_storage
    #     src: /dev/sdb1
    #     fstype: ext4
    #     state: mounted
    #   become: true
    - name: Include role-specific tasks
      ansible.builtin.include_tasks:
        file: tasks-{{ k3s_role }}.yml
