---
- name: Install the NFS external storage provisioner into the cluster
  hosts: localhost
  tasks:
    - name: Ensure the helm repo for nfs-subdir-external-provisioner is added
      kubernetes.core.helm_repository:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: nfs-subdir-external-provsioner
        repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"
    - name: Ensure the nfs-subdir-external-provisioner helm chart is installed
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: nfs-subdir-external-provisioner
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        release_namespace: nfs-system
        create_namespace: true
        values:
          nfs:
            server: "{{ persistent_nfs_server }}"
            path: "{{ persistent_nfs_path }}"
          storageClass:
            defaultClass: true
            onDelete: retain
            pathPattern: "${.PVC.namespace}/${.PVC.name}"
    - name: Ensure local-path is no longer a default storage class
      kubernetes.core.k8s:
        state: patched
        kind: StorageClass
        name: local-path
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "false"
