---
- name: Ensure additional k3s servers are configured for the cluster
  ansible.builtin.shell:
    cmd: curl -sfL https://get.k3s.io | sh -s - server --server={{ k3s_api_url }}
  args:
    creates: /etc/systemd/system/k3s.service
  become: true
- name: Ensure K3S service is started
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true
    daemon_reload: true
  become: true
