---
# tasks file for workstation_chrome
- name: Chrome Install
  block:
    - name: Ensure chrome is installed (Debian)
      block:
        - name: TODO
          debug:
            msg: "Installation of Brave on Debian is not yet implemented."
      when: ansible_distribution == "Debian"
    - name: Ensure chrome is installed (Fedora)
      block:
        - name: Ensure the Google Chrome repo is enabled
          ansible.builtin.yum_repository:
            name: google-chrome
            description: google-chrome
            state: present
            baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
            enabled: true
            gpgcheck: true
            gpgkey: https://dl.google.com/linux/linux_signing_key.pub
            owner: root
            group: root
            mode: '0644'
          become: true
        - name: Ensure Google Chrome is installed
          ansible.builtin.package:
            name: google-chrome-stable
            state: present
            update_cache: true
          become: true
      when: ansible_distribution == "Fedora"
  when: install_chrome
