---
# tasks file for vm-d2 netsniff
- name: install netsniff-ng
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - netsniff-ng
  become: yes
- name: Create a non-priviledge group for netsniff
  group:
    name: netsniff
    gid: 1100
    state: present
- name: Create a non-priviledge user for netsniff
  user:
    name: netsniff
    uid: 1100
    state: present
    group: netsniff
    home: "/nsm/sensor_data/{{ ansible_hostname }}-{{ ansible_interfaces[0] }}"
    shell: /sbin/nologin
- name: Create directory for daily logs
  file:
    path: "/nsm/sensor_data/{{ ansible_hostname }}-{{ ansible_interfaces[0] }}/dailylogs"
    state: directory
    owner: netsniff
    group: netsniff
    mode: 0755
  become: yes
- name: Install netsniff-{{ ansible_interfaces[0] }}.service for systemd
  template:
    path: /etc/systemd/system/netsniff-{{ ansible_interfaces[0] }}.service
    source: netsniff-first-interface.service.js
  become: yes
