# vi: et ts=2 sw=2 foldmethod=indent
---
- name: Ensure the minikube profile directory exists for ansible user
  remote_user: ansible
  ansible.builtin.file:
    path: /home/ansible/.minikube/profiles
    state: directory
- name: Get minikube status
  remote_user: ansible
  ansible.builtin.command: minikube profile list -o json
  changed_when: false
  register: minikube_profiles_json
- name: Store our minikube profile status as a fact
  ansible.builtin.set_fact:
    minikube_profile: "{{ minikube_profiles_json.stdout | from_json | json_query(qry) }}"
  vars:
    qry: 'valid[?Name==''minikube'']'
- name: Handle a non-running profile
  remote_user: ansible
  block:
    - name: Ensure minikube profile is created and started (takes a minute or two)
      ansible.builtin.command:
        argv:
          - minikube
          - start
          - -p
          - "{{ minikube_profile_name }}"
          - --driver={{ minikube_driver }}
          - --cpus={{ minikube_cpus }}
          - --memory={{ minikube_mem }}
          - --addons={{ minikube_addons }}
      failed_when: minikube_status.rc != 0
      changed_when: minikube_status.rc == 0
      register: minikube_status
    - name: Get minikube status (again)
      remote_user: ansible
      ansible.builtin.command: minikube profile list -o json
      changed_when: false
      register: minikube_profiles_json
    - name: Store our minikube profile status as a fact (again)
      ansible.builtin.set_fact:
        minikube_profile: "{{ minikube_profiles_json.stdout | from_json | json_query(qry) }}"
      vars:
        qry: 'valid[?Name==''minikube'']'
  when: minikube_profile[0] is not defined or minikube_profile[0].Status != "Running"
# looks like "minikube start" is fairly idempotent already unless
# you're trying to change memory/cpus on an existing profile. the rest of
# this play is likely not needed.
- name: Ensure minikube is running with the correct resources
  ansible.builtin.assert:
    that:
      - minikube_profile[0].Status == "Running"
      - minikube_profile[0].Config.CPUs >= minikube_cpus | int 
      - minikube_profile[0].Config.Memory >= minikube_mem | int 
    fail_msg:
      - The {{ minikube_profile_name }} profile is not running or is running
      - with insufficient resources.  Run "minikube profile list" to check the
      - state of the profile.  If it is running, it was likely created manually.
      - To fix that, delete the profile using "minikube delete -p {{ minikube_profile_name }}"
      - and run this playbook again (it will create the profile with the
      - corret resources if it doesn't already exist.
