---
- name: Save Cluster Context
  hosts: k8s-dev-s1
  tasks:
    - name: Save the kubernetes config locally
      ansible.builtin.fetch:
        dest: "./"
        flat: true
        src: /etc/kubernetes/admin.conf
      become: true
    # - name: Ensure 127.0.0.1 is replaced with the hostname of the VIP
    #   ansible.builtin.lineinfile:
    #     path: k3s.yaml
    #     regexp: '^(.*server: https://)127\.0\.0\.1(:6443)$'
    #     line: '\1k3s-dev\2'
    #     backrefs: true
    #   delegate_to: localhost
    - name: Ensure the downloaded config file is named kubeconfig
      ansible.builtin.command: mv admin.conf ../kubeconfig
      delegate_to: localhost
