---
- name: Ensure all hosts have the same standard operating environment
  hosts: localhost
  connection: local
  become: yes
  roles:
    - baseline
- name: Ensure local accounts are created for hosts in the home.test domain
  hosts: home_arpa
  roles:
    - local-accounts
- name: Configure Fedora installs as Workstations
  hosts: fedora
  connection: local
  become: yes
  roles:
    - graphical-desktop-environment
