#!/bin/bash
# This script installs Ansible if it is not already installed and then runs the
# setup playbook to configure the workstation.

APARGS="-K -t default -t default --skip-tags disabled"

cat <<DONE
=========================================================================
Verifying network connectivity.
=========================================================================
DONE
ping -q -c 1 8.8.8.8
if [[ $? -ne 0 ]]; then
  echo "Unable to reach the Internet.  Please check your network connectivity."
  exit 1;
fi
echo

# Install Homebrew if not already installed
which -s brew
if [[ $? -ne 0 ]]; then
  cat <<DONE
=========================================================================
Installing homebrew.
=========================================================================
DONE
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# Install Ansible if not already installed
which -s ansible-playbook
if [[ $? -ne 0 ]]; then
  cat <<DONE
=========================================================================
Installing ansible.
=========================================================================
DONE
  brew install ansible
fi

# Do all remaining configuration with Ansible playbook
cat <<DONE
=========================================================================
Running Ansible playbook under caffeinate to prevent hibernation.
=========================================================================
DONE
# In case we are curling this directly from raw.githubusercontent.com
if [[ ! -d ansible ]]; then
  # Install git from Homebrew
  [ -x /usr/local/bin/git ] || brew install git
  # Clone this repo into the home directory
  if [[ ! -d $HOME/home ]]; then
    cd $HOME && /usr/local/bin/git clone https://github.com/dmbrownlee/home.git
  fi
  cd $HOME/home
fi
cd ansible &&
caffeinate -dsu ansible-playbook $APARGS setup.yml
