---
- name: Ensure localhost has the baseline configuration
  hosts: localhost
  connection: local
  roles:
    - role: baseline
      tags:
        - default
    - role: workstation
      tags:
        - workstation
    - role: gamestation
      tags:
        - gamestation
    - role: artstation
      tags:
        - artstation
    - role: mypreferences
      tags:
        - default
