---
- name: Ensure the ansible controller is configured
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure the ansible user has a keypair
      ansible.builtin.user:
        name: ansible
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_comment: ansible@localhost
        ssh_key_file: .ssh/ansible
- name: Ensure all hosts have the same standard operating environment
  hosts: all
  become: yes
  roles:
    - baseline
- name: Ensure local accounts are created
  hosts: all
  become: yes
  roles:
    - local-accounts
- name: Ensure software for hosting containers is installed
  hosts: container_hosts
  become: yes
  roles:
    - podman
- name: Ensure dnsmasq servers are configured
  hosts: dnsmasq_servers
  become: yes
  roles:
    - dnsmasq
- name: Configure Fedora installs as Workstations
  hosts: workstations
  become: yes
  roles:
    - graphical-desktop-environment
