---
- name: Ensure ansible collections are installed
  ansible.builtin.dnf:
    name:
      - ansible-collection-community-general
      - ansible-collection-ansible-posix
    state: present
- name: Ensure ansible group exists
  ansible.builtin.group:
    name: "{{ cfg_group.name }}"
    state: present
    gid: "{{ cfg_group.gid }}"
- name: Ensure ansible user exists
  ansible.builtin.user:
    name: "{{ cfg_account.name }}"
    comment: "{{ cfg_account.comment | default(omit) }}"
    uid: "{{ cfg_account.uid }}"
    group: "{{ cfg_group.name }}"
    groups: wheel
    append: yes
    state: present
- name: Ensure configuration management user can use sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ cfg_account.name }}
    content: '{{ cfg_account.name }} ALL=(ALL) NOPASSWD: ALL'
    owner: root
    group: wheel
    mode: 0440
- name: Ensure linger is enabled for ansible user
  ansible.builtin.file:
    path: /var/lib/systemd/linger/{{ cfg_account.name }}
    state: touch
    owner: root
    group: root
    mode: '0644'
    modification_time: preserve
    access_time: preserve
- name: Ensure there is a systemd for the ansible user
  ansible.builtin.file:
    path: /home/{{ cfg_account.name }}/.config/systemd/user
    state: directory
    owner: "{{ cfg_account.name }}"
    group: "{{ cfg_group.name }}"
    mode: '0755'
- name: Ensure the systemd service and timer files exist for ansible-pull
  ansible.builtin.template:
    src: "{{ item }}.js"
    dest: /home/{{ cfg_account.name }}/.config/systemd/user/{{ item }}
    owner: "{{ cfg_account.name }}"
    group: "{{ cfg_group.name }}"
    mode: '0644'
  loop:
    - ansible-pull.service
    - ansible-pull.timer
# - name: Ensure crontab utility is installed
#   ansible.builtin.dnf:
#     name: /usr/bin/crontab
#     state: present
# - name: Ensure configuration management user has cronjob to run ansible-pull regularly
#   ansible.builtin.cron:
#     name: ansible-pull
#     state: present
#     user: "{{ cfg_account.name }}"
#     job: /usr/bin/ansible-pull --vault-password-file $HOME/.vaultpw -o -U https://github.com/dmbrownlee/home.git -C release
#     minute: '*/10'
