---
- name: Assert this host can use this role
  ansible.builtin.assert:
    that: ansible_distribution in supported_distributions
    fail_msg: "This role is not supported on your host operating system."
- name: Ensure confmgt user exists
  ansible.builtin.user:
    name: confmgt
    state: present
    system: yes
- name: Ensure confmgt user can use sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/confmgt
    content: 'confmgt ALL=(ALL) NOPASSWD: ALL'
    owner: root
    group: root
    mode: 0440
- name: Ensure confmgt user has cronjob to run ansible-pull regularly
  ansible.builtin.cron:
    name: ansible-pull
    state: present
    user: confmgt
    job: /usr/bin/ansible-pull -o -U https://github.com/dmbrownlee/home.git -C release
    minute: '*/10'
