---
- name: Ensure ansible collections are installed
  ansible.builtin.dnf:
    name:
      - ansible-collection-community-general
      - ansible-collection-ansible-posix
    state: present
- name: Ensure ansible group exists
  ansible.builtin.group:
    name: "{{ cfg_group.name }}"
    state: present
    gid: "{{ cfg_group.gid }}"
- name: Ensure ansible user exists
  ansible.builtin.user:
    name: "{{ cfg_account.name }}"
    comment: "{{ cfg_account.comment | default(omit) }}"
    uid: "{{ cfg_account.uid }}"
    group: "{{ cfg_group.name }}"
    groups: wheel
    append: yes
    state: present
- name: Ensure configuration management user can use sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ cfg_account.name }}
    content: '{{ cfg_account.name }} ALL=(ALL) NOPASSWD: ALL'
    owner: root
    group: wheel
    mode: 0440
- name: Ensure the systemd service and timer files exist for ansible-pull
  ansible.builtin.template:
    src: "{{ item }}.js"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - ansible-pull.service
    - ansible-pull.timer
- name: Ensure ansible-pull timer is enabled
  ansible.builtin.file:
    src: /etc/systemd/system/ansible-pull.timer
    dest: /etc/systemd/system/timers.target.wants/ansible-pull.timer
    state: link
    follow: false
    owner: root
    group: root
    mode: '0755'
