---
- name: Ensure ansible collections are installed
  ansible.builtin.dnf:
    name:
      - ansible-collection-community-general
      - ansible-collection-ansible-posix
- name: Ensure ansible group exists
  ansible.builtin.group:
    name: "{{ cfg_group.name }}"
    state: present
    gid: "{{ cfg_group.gid }}"
- name: Ensure ansible user exists
  ansible.builtin.user:
    name: "{{ cfg_account.name }}"
    comment: "{{ cfg_account.comment | default(omit) }}"
    uid: "{{ cfg_account.uid }}"
    group: "{{ cfg_group.name }}"
    groups: wheel
    append: yes
    state: present
- name: Ensure configuration management user can use sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ cfg_account.name }}
    content: '{{ cfg_account.name }} ALL=(ALL) NOPASSWD: ALL'
    owner: root
    group: wheel
    mode: 0440
- name: Ensure crontab utility is installed
  ansible.builtin.dnf:
    name: /usr/bin/crontab
    state: present
- name: Ensure configuration management user has cronjob to run ansible-pull regularly
  ansible.builtin.cron:
    name: ansible-pull
    state: present
    user: "{{ cfg_account.name }}"
    job: /usr/bin/ansible-pull --vault-password-file $HOME/.vaultpw -o -U https://github.com/dmbrownlee/home.git -C release
    minute: '*/10'
