---
- name: Ensure ansible collections are installed
  ansible.builtin.dnf:
    name:
      - ansible-collection-community-general
      - ansible-collection-ansible-posix
    state: present
- name: Ensure default directory for custom facts exists
  ansible.builtin.file:
    path: /etc/ansible/fact.d
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Ensure any custom facts have been installed
  ansible.builtin.debug:
    msg: installing custom facts
- name: Ensure setup is run
  ansible.builtin.setup:
- name: Ensure provisioning group exists
  ansible.builtin.group:
    name: "{{ provisioning.group.name }}"
    state: present
    gid: "{{ provisioning.group.gid }}"
- name: Ensure provisioning user exists
  ansible.builtin.user:
    name: "{{ provisioning.user.name }}"
    comment: "{{ provisioning.user.comment | default(omit) }}"
    uid: "{{ provisioning.user.uid }}"
    group: "{{ provisioning.group.name }}"
    groups: wheel
    append: yes
    state: present
- name: Ensure provisioning user can use sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ provisioning.user.name }}
    content: '{{ provisioning.user.name }} ALL=(ALL) NOPASSWD: ALL'
    owner: root
    group: wheel
    mode: 0440
- name: Ensure the systemd service and timer files exist for ansible-pull
  ansible.builtin.template:
    src: "{{ item }}.js"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - ansible-pull.service
    - ansible-pull.timer
- name: Ensure ansible-pull timer is enabled
  ansible.builtin.file:
    src: /etc/systemd/system/ansible-pull.timer
    dest: /etc/systemd/system/timers.target.wants/ansible-pull.timer
    state: link
    follow: false
    owner: root
    group: root
    mode: '0755'
- name: Ensure provisioning user can connect using keys
  ansible.posix.authorized_key:
    user: "{{ provisioning.user.name }}"
    state: present
    key: "{{ lookup('file', '/etc/ansible/keys/' + provisioning.user.name + '.pub') }}"
