---
- name: Ensure ansible user exists
  ansible.builtin.user:
    name: ansible
    state: present
    system: yes
- name: Ensure ansible user can use sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible
    content: 'ansible ALL=(ALL) NOPASSWD: ALL'
    owner: root
    group: wheel
    mode: 0440
- name: Ensure crontab utility is installed
  ansible.builtin.dnf:
    name: /usr/bin/crontab
    state: present
- name: Ensure ansible user has cronjob to run ansible-pull regularly
  ansible.builtin.cron:
    name: ansible-pull
    state: present
    user: ansible
    job: /usr/bin/ansible-pull --vault-password-file $HOME/.vaultpw -o -U https://github.com/dmbrownlee/home.git -C release
    minute: '*/10'
