---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ${DIST:-debian12}-workstation
    image: "docker.io/geerlingguy/docker-${DIST:-debian12}-ansible:latest"
    command: "/sbin/init"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  options:
    extra_vars: '{"dnf_packages":[],"addons":{"brave":true,"chrome":true,"icaclient":true,"steam":true,"zoom":true}}'
  log: true
verifier:
  name: ansible
