---
# Use the RPMs from cert
- name: Add EPEL and CERT repos
  yum: name={{ item }} state=present
  with_items:
  - "epel-release"
  - "https://forensics.cert.org/cert-forensics-tools-release-el7.rpm"
  become: yes
- rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-cert-forensics-2018-04-07
- name: Add the SiLK CERT forensics tools
  yum: name={{ item }} state=present
  with_items:
  - "silk-common"
  - "silk-analysis"
  - "silk-flowcap"
  - "silk-rwflowappend"
  - "silk-rwflowpack"
  - "silk-rwreceiver"
  - "silk-rwsender"
  - "yaf"
  - "super_mediator"
  become: yes
# - name: Download sample flow data
#   unarchive:
#     src: http://tools.netsa.cert.org/silk/refdata/FCCX-silk.tar.gz
#     dest: /root
#     remote_src: yes
#     mode: 0755
#     owner: root
#     group: root
#     creates: /root/FCCX-silk
#   become: yes
# - name: Download sample pcap data
#   unarchive:
#     src: http://tools.netsa.cert.org/silk/refdata/FCCX-pcap.tar.gz
#     dest: /root
#     remote_src: yes
#     mode: 0755
#     owner: root
#     group: root
#     creates: /root/FCCX-data
#   become: yes
