---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: fedora38-pull
    image: "docker.io/geerlingguy/docker-fedora38-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
