---
- name: Ensure system packages are installed
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ system_packages }}"
  when:
    - system_packages is defined
    - (system_packages | length > 0)
