apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photos
  namespace: immich
spec:
  ingressClassName: traefik
  rules:
    - host: {{ cnames.photos }}
      http:
        paths:
        - backend:
            service:
              name: immich-server
              port:
                number: 3001
          path: /
          pathType: Prefix
