---
# Bash configuration
- name: Ensure directory for bash customizations exists
  file:
    path: "{{ ansible_user_dir }}/.bashrc.d"
    state: directory
    mode: '0700'
- name: Ensure {{ ansible_user_dir }}/.bashrc exists
  file:
    path: "{{ ansible_user_dir }}/.bashrc"
    state: file
    mode: '0644'
- name: Ensure ~/.bashrc.d/ files are sourced from .bashrc
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    marker: "# {mark}"
    marker_begin: "=== ANSIBLE MANAGED BLOCK BEGIN: Source files in .bashrc.d"
    marker_end: "END: .bashrc.d"
    block: |
      if [[ -d "$HOME/.bashrc.d" ]]; then
        source $HOME/.bashrc.d/*
      fi
- name: Ensure bash customizations are installed
  template:
    src: ".bashrc.d/{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.bashrc.d/{{ item }}"
    mode: '0644'
  with_items:
  - '90user_bin_dir'
