---
# Git configuration
- name: Ensure global git settings have been configured
  git_config:
    name: '{{ item.name }}'
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: 'user.name', value: '{{ git_user_name }}' }
    - { name: 'user.email', value: '{{ git_user_email }}' }
