---
#- name: Remove all crap from Dock
#  shell: dockutil --remove '{{ item }}'
#  ignore_errors: true
#  with_items: dockitems_to_remove
- name: Remove all crap from Dock
  command:
    cmd: dockutil --remove all --no-restart
  notify: launcher-restart-macosx
- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}' --no-restart
  loop: "{{ dockitems }}"
  notify: launcher-restart-macosx
- name: Fix order
  command:
    cmd: dockutil --move '{{ item.name }}' --position {{ item.pos }} --no-restart
  loop: "{{ dockitems }}"
  notify: launcher-restart-macosx
- name: Ensure Recents is disabled
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    state: present
    value: 0
  notify: launcher-restart-macosx
- osx_defaults:
    domain: com.apple.dock
    key: recent-apps
    state: present
    type: array
    value: []
  notify: launcher-restart-macosx
