---
# tasks file for workstation
- name: Workstation (Fedora)
  block:
    - name: Ensure the ansible user is hidden from the login screen
      ansible.builtin.copy:
        src: ansible
        dest: /var/lib/AccountsService/users
        mode: '0600'
      notify: restart_display_manager
    - name: Ensure Fedora workstation specific packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ dnf_packages }}"
      when:
        - dnf_packages is defined
        - (dnf_packages | length > 0)
    - name: Ensure default systemd target is graphical.target
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
  when: ansible_distribution == "Fedora"
- name: Workstation (Debian)
  block:
    - name: Ensure the ansible user is hidden from the login screen
      ansible.builtin.copy:
        src: ansible
        dest: /var/lib/AccountsService/users
        mode: '0600'
      notify: restart_display_manager
    - name: Ensure Debian workstation specific packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ debian_workstation_packages }}"
      when:
        - debian_workstation_packages is defined
        - (debian_workstation_packages | length > 0)
    - name: Ensure default systemd target is graphical.target
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
  when: ansible_distribution == "Debian"
- name: Add-on software
  block:
    - name: Install Brave
      ansible.builtin.include_role:
        name: workstation_brave
      when: addons.brave
    - name: Install Brave
      ansible.builtin.include_role:
        name: workstation_chrome
      when: addons.chrome
    - name: Install ICAClient
      ansible.builtin.include_role:
        name: workstation_icaclient
      when: addons.icaclient
    - name: Install Steam
      ansible.builtin.include_role:
        name: workstation_steam
      when: addons.steam
    - name: Install Zoom
      ansible.builtin.include_role:
        name: workstation_zoom
      when: addons.zoom
