---
- name: bash configuration
  include_tasks: bash.yml
- name: tmux configuration
  include_tasks: tmux.yml
- name: git configuration
  include_tasks: git.yml
- name: vim configuration
  include_tasks: vim.yml
