---
# tasks file for workstation
- name: Workstation (Fedora)
  block:
    - name: Ensure the ansible user is hidden from the login screen
      ansible.builtin.copy:
        src: ansible
        dest: /var/lib/AccountsService/users
        mode: '0600'
      notify: restart_display_manager
    - name: Ensure Fedora workstation specific packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ dnf_packages }}"
      when:
        - dnf_packages is defined
        - (dnf_packages | length > 0)
    - name: Ensure default systemd target is graphical.target
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
  when: ansible_distribution == "Fedora"
