---
- name: Ensure system brews are installed
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ system_brews }}"
  when:
    - system_brews is defined
    - (system_brews | length > 0)
- name: Ensure system casks are installed
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ system_casks }}"
  when:
    - system_casks is defined
    - (system_casks | length > 0)
- name: Ensure a special folder for software downloads exists
  file:
    path: "{{ ansible_user_dir }}/Software"
    state: directory
    mode: '0755'
- name: Get a list of apps installed under /Applications
  command:
    cmd: "find /Applications -type d -name '*.app' -maxdepth 1"
  register: installed_apps
  changed_when: false
- name: Get a list of installed packages
  command:
    cmd: "pkgutil --pkgs"
  register: installed_packages
  changed_when: false
- name: Ensure system software distributed as dmg files has been downloaded
  include_tasks: macosx-dmg-installer.yml
  vars:
    dmg: "{{ item }}"
  loop: "{{ system_dmgs }}"
  when:
    - not item.artifact in installed_apps.stdout_lines
    - not item.artifact in installed_packages.stdout_lines
