---
- name: Ensure system packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ system_packages }}"
  when:
    - system_packages is defined
    - (system_packages | length > 0)
  become: yes
- name: Ensure a special folder for software downloads exists
  file:
    path: "{{ ansible_user_dir }}/Software"
    state: directory
    mode: '0755'
