- name: Ensure the immich namespace exists
  kubernetes.core.k8s:
    name: immich
    api_version: v1
    kind: Namespace
    state: present
- name: Ensure the helm repo for immich is added
  kubernetes.core.helm_repository:
    kubeconfig: "{{ k3s_local_kubeconfig_path }}"
    name: immich
    repo_url: "https://immich-app.github.io/immich-charts"
- name: Ensure the PVC for the immich library has been created
  kubernetes.core.k8s:
    kubeconfig: "{{ k3s_local_kubeconfig_path }}"
    state: present
    template: immich-library-pvc.yaml
- name: Ensure the immich helm chart is installed
  kubernetes.core.helm:
    kubeconfig: "{{ k3s_local_kubeconfig_path }}"
    name: immich
    chart_ref: immich/immich
    release_namespace: immich
    create_namespace: true
    values:
      image:
        tag: v1.115.0
      immich:
        metrics:
          enabled: true
        persistence:
          library:
            existingClaim: immich-library-pvc
      postgresql:
        enabled: true
      redis:
        enabled: true
      # server:
      #   ingress:
      #     main:
      #       enabled: true
      #       hosts:
      #         - host: photos.site1.thebrownleefamily.net
      #           paths:
      #             - path: "/"
      machine-learning:
        persistence:
          cache:
            storageClass: nfs-client
      persistence:
        library:
          existingClaim: immich-library-pvc
          globalMounts:
            - path: /usr/src/app/upload
- name: Ensure the photos ingress configuration has been applied
  kubernetes.core.k8s:
    kubeconfig: "{{ k3s_local_kubeconfig_path }}"
    state: present
    template: photos-ingress.yaml
