---
# tasks file for vm-vertical-monitor
#- name: Configuring vertical virtual consoles
- name: Configuring vertical virtual consoles
  replace:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*[^3])"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 fbcon=rotate:3"'
  become: yes
  notify:
  - grub2-mkconfig
