---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: fedora37
    image: "docker.io/geerlingguy/docker-fedora37-ansible:latest"
    command: "/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
