---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ${DIST:-debian12}-ROLE_NAME
    image: "docker.io/geerlingguy/docker-${DIST:-debian12}-ansible:latest"
    command: "/sbin/init"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  # Put sensitive variables in site_data.yml which is ignored by git and have
  # molecule include them with the "-e @site_data.yml" extra_args option by
  # uncommenting this two lines.
  # options:
  #   e: "@site_data.yml"
  log: true
verifier:
  name: ansible
