---
- name: Ensure confmgt account is unlocked
  ansible.builtin.user:
    name: confmgt
    password_lock: False
  become: yes
#
# available_accounts:
#   Defined in the role variables, these are all the accounts available to
#   any host.
#
# local_accounts:
#   Defined in the host's vars, this is the list of usernames from the
#   available_accounts which will be created on this host.
- name: Ensure list of available accounts is included
  ansible.builtin.include_vars: available_accounts.yml
- name: Ensure local account for {{ user.username }} exists
  ansible.builtin.user:
    name: "{{ user.username }}"
    uid: "{{ user.uid | default(omit) }}"
    comment: "{{ user.comment | default(omit) }}"
    groups: "{{ user.groups | default(omit) }}"
    password: "{{ user.password | default(omit) }}"
    password_lock: "{{ user.password_lock | default('True') }}"
    state: present
  become: yes
  when: user.username in local_accounts
  loop: "{{ available_accounts }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
