---
# available_accounts:
#   Defined in the role variables, these are all the accounts available to
#   any host.
#
# local_accounts:
#   Defined in the host's vars, this is the list of usernames from the
#   available_accounts which will be created on this host.
- name: Ensure local groups exist
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.gid }}"
    state: present
  when: directory_groups is defined
  loop: "{{ directory_groups }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
- name: Ensure local accounts exist
  ansible.builtin.user:
    name: "{{ user.name }}"
    uid: "{{ user.uid }}"
    comment: "{{ user.comment | default(omit) }}"
    group: "{{ user.group }}"
    groups: "{{ user.groups | default(omit) }}"
    append: true
    password: "{{ user.password | default(omit) }}"
    password_lock: "{{ user.password_lock | default('true') }}"
    state: present
  when: directory_users is defined
  loop: "{{ directory_users }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
