---
- name: Ensure local groups exist
  ansible.builtin.include_tasks: add_local_group.yml
  vars:
    group: "{{ domain_groups | selectattr('name', 'eq', item.name) | last }}"
  when:
    - local_groups is defined
  loop: "{{ local_groups | list }}"
- name: Ensure local users exist
  ansible.builtin.include_tasks: add_local_user.yml
  vars:
    user: "{{ domain_users | selectattr('name', 'eq', item.name) | last }}"
  when:
    - local_users is defined
  loop: "{{ local_users | list }}"
