---
- name: Ensure local groups exist
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state }}"
  when:
    - local_groups is defined
  loop: "{{ local_groups | list }}"
- name: Ensure local users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_password: 'on_create'
    password: "{{ item.password }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    append: "{{ (item.groups is defined) | ternary(true, omit) }}"
  when:
    - local_users is defined
  loop: "{{ local_users | list }}"
