---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora
    image: docker.io/geerlingguy/docker-fedora37-ansible
    #image: registry.fedoraproject.org/fedora
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
