---
# tasks file for sshd
- name: Ensure baseline packages are installed (Fedora)
  ansible.builtin.dnf:
    name: openssh-server
    state: latest
  when: ansible_distribution == "Fedora"
- name: Ensure baseline packages are installed (Debian)
  ansible.builtin.apt:
    name: openssh-server
    state: present
  when: ansible_distribution == "Debian"
# Note: sshd has to be started prior to updating the configuration so that
# the /run/sshd directory will exist and config validation will work.
- name: Ensure sshd is started
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: true
- name: Ensure sshd is configured
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: restart_sshd
