---
system_brews:
  - ansible-lint
  - dockutil
  - tmux
system_casks:
  - google-chrome
dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - News
  - Books
  - Podcasts
  - TV
  - App Store
  - System Preferences
  - Calendar
dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Terminal
    path: /System/Applications/Utilities/Terminal.app
    pos: 2
  - name: GNS3
    path: /Applications/GNS3.app
    pos: 3
