---
- name: Assert this host can use this role
  assert:
    that: ansible_distribution in supported_distributions
    fail_msg: "This role is not supported on your host operating system."
- name: Ensure OS specific vars have been loaded
  include_vars: "{{ ansible_distribution | lower }}.yml"
- name: role packages
  include_tasks: "packages-{{ ansible_distribution | lower }}.yml"
