---
- name: Kickstart post configuration
  hosts: localhost
  vars_files:
    - vars_files/local_users.yml
  tasks:
    - name: Ensure all packages are updated
      yum:
        name: '*'
        state: latest
      tags:
      - devexclude
    - name: Ensure password authentication for SSH is disabled
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication yes.*$'
        replace: 'PasswordAuthentication no'
    - name: Ensure the password for the root account is locked
      user:
        name: root
        password_lock: yes
    - name: Ensure a local admin user account is created if requested
      user:
        name: "{{ local_user }}"
        state: present
        groups: wheel
      become: yes
      when: local_user is defined
      tags:
      - dev
      - local_user
    - name: Ensure public key is installed for local_user
      authorized_key:
        key: "{{ local_user_pubkey_url }}"
        state: present
        user: "{{ local_user }}"
        comment: "{{ local_user_pubkey_comment }}"
      become: yes
      when: local_user_pubkey_url is defined
      tags:
      - dev
      - local_user
