---
- name: Kickstart post configuration
  hosts: localhost
  tasks:
    - name: Ensure all packages are updated
      yum:
        name: '*'
        state: latest
      tags:
      - devexclude
    - name: Ensure public key is installed for root
      authorized_key:
        key: https://github.com/dmbrownlee.keys
        state: present
        user: root
        comment: "Installed from GitHub via kickstart"
    - name: Ensure password authentication for SSH is disabled
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication yes.*$'
        replace: 'PasswordAuthentication no'
    - name: Ensure SSHD is enabled at boot but stopped during install
      systemd:
        name: sshd
        state: reloaded
        enabled: yes
    - name: Ensure the password for the root account is locked
      user:
        name: root
        password_lock: yes
    - name: Ensure local users are created
      user:
        name: "{{ item.name }}"
        state: present
        comment: "{{ itme.comment | default(user_default.comment) }}"
      become: yes
      loop: "{{ local_users }}"
      when: local_users is defined
      tags:
      - dev
      - localusers
      # FYI: ansible localhost -m debug -a "msg='{{ lookup('pipe','sed -n "s/^SHELL=//p" /etc/default/useradd') }}'"
