---
# This playbook configures the guest OS as Vagrant creates the VMs.
- name: Common configuration
  hosts: all
  roles:
    - role: vm-common-packages

- name: d1 configuration
  hosts: d1.home.test
  roles:
    - role: vm-d1
    - role: vm-silk

- name: d2 configuration
  hosts: d2.home.test
  roles:
    - role: vm-d2
    - role: vm-silk
