---
# tasks file for workstation_icaclient
- name: Ensure icaclient is installed (Debian)
  block:
    - name: Install Citrix Workspace packages
      ansible.builtin.apt:
        deb:
          http://{{ local_repo.cname }}.{{ site_data.domain }}/debian/{{ item }}
      loop: "{{ icaclient_debs }}"
  when: ansible_distribution == "Debian"
- name: Ensure icaclient is installed (Fedora)
  block:
    - name: Ensure ICAClient is installed
      ansible.builtin.dnf:
        name: ICAClient
        state: present
  when: ansible_distribution == "Fedora"
