---
# tasks file for workstation_icaclient
- name: Install Citrix ICA Client
  block:
    - name: Ensure icaclient is installed (Debian)
      ansible.builtin.debug:
        msg: "icaclient installation on Debian is not implemented yet."
      when: ansible_distribution == "Debian"
    - name: Ensure icaclient is installed (Fedora)
      ansible.builtin.dnf:
        name: ICAClient
        state: present
      when: ansible_distribution == "Fedora"
  when: install_icaclient
