---
# tasks file for vm-netgear
- name: Installing packages specific to supporting netgear functionality
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - python-firewall
- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  become: yes
- name: Set external as default policy
  command: firewall-cmd --set-default-zone=home
  become: yes
- name: Add home firewall services
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes zone=home
  become: yes
  with_items:
    - dns
    - dhcp
    - ssh
- name: Remove default firewall services from work
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=work
  become: yes
  with_items:
    - dhcpv6-client
    - ssh
- name: Remove default firewall services from internal
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=work
  become: yes
  with_items:
    - dhcpv6-client
    - mdns
    - samba-client
    - ssh
- name: Remove default firewall services from external
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=external
  become: yes
  with_items:
    - dhcpv6-client
    - mdns
    - samba-client
    - ssh
- name: Remove default firewall services from dmz
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=dmz
  become: yes
  with_items:
    - ssh
- name: Remove default firewall services from public
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=public
  become: yes
  with_items:
    - dhcpv6-client
    - ssh
