---
# tasks file for vm-d1 interfaces
#
# - The second interface is active at boot and configures itself using DHCP
#   on the home network. Note: This is because PXE boot fails when using
#   the first interface.
# - The first interface is not activated and is the interface used to
#   sniff packets
#
- name: install needed network manager libs
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - NetworkManager-glib
  become: yes
#
# Initialize the configs
#
- name: Enable NetworkManager
  service:
    name: NetworkManager
    state: started
    enabled: yes
  become: yes
- name: Apply default interface config
  include:
    src: interface.yml
  vars:
    this_interface: "{{ item }}"
  with_items:
    - "{{ ansible_interfaces[1] }}"
    - "{{ ansible_interfaces[2] }}"
  become: yes
#
# Configure first interface
#
- name: Configure first interface for dhcp at boot
  nmcli:
    ifname: "{{ ansible_interfaces[1] }}"
    type: ethernet
    conn_name: "{{ ansible_interfaces[1] }}"
    state: present
    autoconnect: yes
  become: yes
- name: Use NetworkManager to configure zone for interface on home network
  command: nmcli c mod {{ ansible_interfaces[1] }} connection.zone home
  become: yes
#
# Configure second interface
#
- name: Use NetworkManager to configure zone for interface on trusted network
  command: nmcli c mod {{ ansible_interfaces[2] }} connection.zone trusted
  become: yes
#
# Restart NetworkManager
#
- name: Enable NetworkManager
  service:
    name: NetworkManager
    state: restarted
  become: yes
