---
# tasks file for vm-d1 pxeserver
- name: Install packages for DNS, DHCP, PXE server
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - syslinux
    - tftp-server
    - vsftpd
- name: Copy syslinux files to TFTP directory
  command: rsync -avPS /usr/share/syslinux/ /var/lib/tftpboot/
  become: yes
- name: Make /var/lib/tftpboot/pxelinux.cfg
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
  become: yes
- name: Make /var/lib/tftpboot/centos7
  file:
    path: /var/lib/tftpboot/centos7
    state: directory
  become: yes
- name: Create PXE default menu
  template:
    src: default.js
    dest: /var/lib/tftpboot/pxelinux.cfg/default
  become: yes
- name: Enable and start services
  service: name={{ item }} enabled=yes
  become: yes
  with_items:
    - vsftpd
- name: Update firewall services
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes zone=home
  become: yes
  with_items:
    - ftp
- name: Open TFTP (69/udp) and PXE (4011/udp) firewall ports
  firewalld: port={{ item }} state=enabled permanent=yes immediate=yes zone=home
  become: yes
  with_items:
    - 69/udp
    - 4011/udp
