alias fwctl="sudo /usr/bin/firewall-cmd"

function sco () {
  screen -ls | /usr/bin/egrep -q 'outer-frame.*(Detached)'
  if [[ $? -eq 0 ]]; then
    screen -r outer-frame
  else
    screen -S outer-frame -c ~/.screenrc-outer-frame
  fi
}
