---
- name: Ensure OS specific vars have been loaded
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Fedora"
    fail_msg: "The fedora-workstation role should only be used on Fedora machines."
- name: Ensure the Google Chrome repo is enabled for machines with Chrome
  ansible.builtin.yum_repository:
    name: google-chrome
    description: Where does this end up?
    state: present
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    owner: root
    group: root
    mode: '0644'
  when:
    - chrome_should_be_installed is defined
    - chrome_should_be_installed
- name: Ensure the RPM Fusion free repo is enabled for machines with Steam
  ansible.builtin.dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  when:
    - steam_should_be_installed is defined
    - steam_should_be_installed
- name: Ensure the RPM Fusion nonfree repo is enabled for machines with Steam
  ansible.builtin.dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  when:
    - steam_should_be_installed is defined
    - steam_should_be_installed
- name: Ensure dnf packages are installed
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_packages }}"
  when:
    - ansible_pkg_mgr == 'dnf'
    - dnf_packages is defined
    - (dnf_packages | length > 0)
- name: Ensure default systemd target is graphical.target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
- name: Ensure autofs is enabled
  ansible.builtin.service:
    name: autofs
    state: started
    enabled: yes
- name: Ensure the ansible user is hidden from the display manager login screen
  ansible.builtin.copy:
    src: ansible
    dest: /var/lib/AccountsService/users
    mode: '0600'
  notify: restart_display_manager
- name: Ensure Google Chrome is installed if requested
  ansible.builtin.package:
    name: google-chrome-stable
    state: present
  when:
    - chrome_should_be_installed is defined
    - chrome_should_be_installed
- name: Ensure Steam is installed if requested
  ansible.builtin.package:
    name: steam
    state: present
  when:
    - steam_should_be_installed is defined
    - steam_should_be_installed
