---
- name: Ensure OS specific vars have been loaded
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Fedora"
    fail_msg: "The fedora-workstation role should only be used on Fedora machines."
- name: Ensure the Google Chrome repo is enabled for machines with Chrome
  ansible.builtin.yum_repository:
    name: google-chrome
    description: google-chrome
    state: present
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    owner: root
    group: root
    mode: '0644'
  when:
    - chrome_should_be_installed is defined
    - chrome_should_be_installed
- name: Ensure the RPM Fusion free repo is enabled for machines with Steam
  ansible.builtin.dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    update_cache: yes
    disable_gpg_check: yes
  when:
    - steam_should_be_installed is defined
    - steam_should_be_installed
- name: Ensure the RPM Fusion nonfree repo is enabled for machines with Steam
  ansible.builtin.dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    update_cache: yes
    disable_gpg_check: yes
  when:
    - steam_should_be_installed is defined
    - steam_should_be_installed
- name: Ensure autofs is installed
  ansible.builtin.dnf:
    name: autofs
    update_cache: yes
- name: Ensure old credential file for CIFS is removed
  ansible.builtin.file:
    path: /etc/creds/{{ item.filename }}
    state: absent
  loop: "{{ cifscreds }}"
  when:
    - cifscreds is defined
    - cifscreds | length > 0
- name: Ensure old autofs configuration for CIFS is removed
  ansible.builtin.file:
    path: /etc/auto.master.d/cifs.autofs
    state: absent
  register: autofs_config
- name: Ensure autofs is restarted if the config changed
  ansible.builtin.service:
    name: autofs
    state: restarted
    enabled: yes
  when: autofs_config.changed
- name: Ensure old directories for automounting CIFS have been removed
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /cifs
    - /etc/creds
- name: Ensure autofs is enabled
  ansible.builtin.service:
    name: autofs
    state: started
    enabled: yes
- name: Ensure the ansible user is hidden from the display manager login screen
  ansible.builtin.copy:
    src: ansible
    dest: /var/lib/AccountsService/users
    mode: '0600'
  notify: restart_display_manager
- name: Ensure local repo is enabled
  ansible.builtin.yum_repository:
    name: home
    description: Repo for locally managed packages
    state: present
    baseurl: "{{ home_repo.baseurl }}"
    enabled: yes
    gpgcheck: no
    owner: root
    group: root
    mode: '0644'
- name: Ensure baseline packages are installed
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ dnf_packages }}"
  when:
    - ansible_pkg_mgr == 'dnf'
    - dnf_packages is defined
    - (dnf_packages | length > 0)
- name: Ensure local baseline packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ home_repo.packages }}"
  when:
    - home_repo.packages is defined
    - (home_repo.packages | length > 0)
- name: Ensure Google Chrome is installed if requested
  ansible.builtin.package:
    name: google-chrome-stable
    state: present
    update_cache: yes
  when:
    - chrome_should_be_installed is defined
    - chrome_should_be_installed
- name: Ensure Steam is installed if requested
  ansible.builtin.package:
    name: steam
    state: present
    update_cache: yes
  when:
    - steam_should_be_installed is defined
    - steam_should_be_installed
- name: Ensure Zoom is installed if requested
  ansible.builtin.package:
    name: zoom
    state: present
    update_cache: yes
  when:
    - zoom_should_be_installed is defined
    - zoom_should_be_installed
- name: Ensure Citrix Workspace is installed if requested
  ansible.builtin.package:
    name: ICAClient
    state: present
    update_cache: yes
  when:
    - icaclient_should_be_installed is defined
    - icaclient_should_be_installed
- name: Ensure default systemd target is graphical.target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
