---
- name: Ensure OS specific vars have been loaded
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Fedora"
    fail_msg: "The fedora-workstation role should only be used on Fedora machines."
- name: Ensure the ansible user is hidden from the display manager login screen
  ansible.builtin.copy:
    src: ansible
    dest: /var/lib/AccountsService/users
    mode: '0600'
  notify: restart_display_manager
- name: Ensure local repo is enabled
  ansible.builtin.yum_repository:
    name: home
    description: Repo for locally managed packages
    state: present
    baseurl: "{{ home_repo.baseurl }}"
    enabled: yes
    gpgcheck: no
    owner: root
    group: root
    mode: '0644'
- name: Ensure baseline packages are installed
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ dnf_packages }}"
  when:
    - ansible_pkg_mgr == 'dnf'
    - dnf_packages is defined
    - (dnf_packages | length > 0)
- name: Ensure local baseline packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ home_repo.packages }}"
  when:
    - home_repo.packages is defined
    - (home_repo.packages | length > 0)
- name: Ensure Zoom is installed if requested
  ansible.builtin.package:
    name: zoom
    state: present
    update_cache: yes
  when:
    - zoom_should_be_installed is defined
    - zoom_should_be_installed
- name: Ensure Citrix Workspace is installed if requested
  ansible.builtin.package:
    name: ICAClient
    state: present
    update_cache: yes
  when:
    - icaclient_should_be_installed is defined
    - icaclient_should_be_installed
- name: Ensure default systemd target is graphical.target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
