#!/bin/bash
OS=$(uname)

if [[ "$OS" == "Darwin" ]]; then
  EASY_INSTALL=/usr/local/bin/easy_install
  PIP=/usr/local/bin/pip
  ANSIBLE=/usr/local/bin/ansible-playbook
  if [[ ! -x $PIP ]]; then
    sudo -H $EASY_INSTALL pip
  fi
  sudo -H $PIP install -q -U pip
  if [[ ! -x $ANSIBLE ]]; then
    sudo -H $PIP install ansible
  fi
  sudo -H $PIP install -q -U ansible
fi
