---
- name: Ensure sshpass is installed on the local host (since -k requires it)
  hosts: localhost
  become: true
  remote_user: "{{ provisioning.username }}"
  tasks:
    - name: Ensure the sshpass utility is installed
      ansible.builtin.apt:
        name: sshpass
- name: Authorize Keys
  hosts: all:!localhost
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data"
  remote_user: "{{ provisioning.username }}"
  gather_facts: true
  tasks:
    - name: Ensure provisioning account's current key is authorized
      ansible.posix.authorized_key:
        user: "{{ provisioning.username }}"
        key: "{{ lookup('file','{{ provisioning.pubkey_file }}') }}"
        manage_dir: true
        exclusive: true
