---
# This playbook configures the guest OS as Vagrant creates the VMs.
- name: Common configuration
  hosts: all
  roles:
    - role: vm-common-packages

- name: ks configuration
  hosts: ks
  roles:
    - role: vm-vertical-monitor
