---
- name: Ensure netbox servers are configured
  hosts: netbox
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data.yml"
  remote_user: "{{ provisioning.username }}"
  become: true
  roles:
    - netbox
