---
- name: Configure Zoom
  hosts: workstations
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data.yml"
  remote_user: "{{ provisioning.username }}"
  become: true
  roles:
    - workstation_zoom
