---
- name: Configure Fedora installs as Workstations
  hosts: fedora_workstations
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data"
  remote_user: "{{ provisioning.username }}"
  become: true
  roles:
    - fedora-workstation
