---
- name: Ensure autofs is configured on nasclients
  hosts: autofs
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data"
  remote_user: "{{ provisioning.username }}"
  become: true
  roles:
    - autofs
