---
- name: Configure Chrome
  hosts: workstations
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data"
  remote_user: "{{ provisioning.username }}"
  become: true
  roles:
    - workstation_chrome
