---
- name: Ensure mirror hosts are configured
  hosts: mirrors
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data.yml"
  remote_user: "{{ provisioning.username }}"
  become: true
  roles:
    - mirror
