---
- name: Ensure repo hosts are configured
  hosts: repos
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data.yml"
  remote_user: "{{ provisioning.username }}"
  become: true
  roles:
    - local_repo
