---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: fedora38-steam
    image: "docker.io/geerlingguy/docker-fedora38-ansible:latest"
    command: "/sbin/init"
    pre_build_image: true
  - name: debian12-steam
    image: "docker.io/geerlingguy/docker-debian12-ansible:latest"
    command: "/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
  options:
    "extra-vars": "install_steam=true"
verifier:
  name: ansible
