---
- name: Configure load balancers
  hosts: all
  become: yes
  tasks:
    # - name: Display all variables/facts known for a host
    #   ansible.builtin.debug:
    #     var: hostvars[inventory_hostname]
    - name: Ensure package cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Ensure default system packages are up to date
      ansible.builtin.apt:
        upgrade: yes
        autoclean: yes
    - name: Ensure keepalived and haproxy are installed
      ansible.builtin.apt:
        name:
          - keepalived
          - haproxy
          - nginx
    - name: Ensure haproxy is configured
      ansible.builtin.template:
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
        src: haproxy.cfg.j2
      register: haproxy_config
    - name: Ensure haproxy is restarted if config changes
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: true
      when: haproxy_config.changed
    - name: Ensure drop-in directory for keepalived configs exists
      ansible.builtin.file:
        path: /etc/keepalived/conf.d
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Ensure keepalived is configured
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: include /etc/keepalived/conf.d/*.conf
        owner: root
        group: root
        mode: '0644'
    - name: Ensure test VIP exists
      ansible.builtin.template:
        dest: /etc/keepalived/conf.d/testvip.conf
        owner: root
        group: root
        mode: '0644'
        src: keepalived.conf.j2
      register: keepalived_config
    - name: Ensure keepalived is restarted if config changes
      ansible.builtin.systemd:
        name: keepalived
        state: restarted
        enabled: true
      when: keepalived_config.changed
