---
- name: Ensure ansible control host can fetch content from mirror
  hosts: molecule
  tasks:
    - name: Ensure ansible control host can fetch content from mirror
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}/debian/verify.html"
        follow_redirects: none
        method: GET
      register: result
      until: result.status == 200
      retries: 5
      delay: 2
      # failed_when: result is failed or "'working!' not in result.content"
    # - name: Prove registered result does not have a content attribute
    #   debug:
    #     var: result
