---
# This playbook is for post-role verificationl
- name: Ensure ansible control host can fetch content from repo
  hosts: molecule
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data.yml"
  tasks:
    - name: Ensure ansible control host can fetch content from repo
      ansible.builtin.uri:
        url:
          "http://{{ ansible_default_ipv4.address }}/debian/mirror_root.html"
        follow_redirects: none
        method: GET
        headers:
          host: "{{ mirrors.cname }}.{{ site_data.domain }}"
      register: result
      until: result.status == 200
      retries: 5
      delay: 2
